import {
	Home,
	Login,
	Registration,
	CodePage,
	ForgotPassword,
	ResetPassword,
	CodeEditor,
	ChooseTask,
	Profile,
	SolutionResult,
} from "@/pages/index";

import type { AppPage } from "@/shared/index.ts";

export const mainPageRoutes: AppPage[] = [
	{
		path: "/",
		label: "Home",
		component: Home,
		showInNavbar: true,
		showNavBar: true,
		access: "public",
	},
	{
		path: "/login",
		label: "Login",
		component: Login,
		showInNavbar: true,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/Registration",
		label: "Registration",
		component: Registration,
		showInNavbar: true,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/confirm-email",
		label: "Confirm email",
		component: CodePage,
		showInNavbar: false,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/forgot-password",
		label: "Forgot password",
		component: ForgotPassword,
		showInNavbar: false,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/reset-password",
		label: "Reset password",
		component: ResetPassword,
		showInNavbar: false,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/CodePage",
		label: "CodePage",
		component: CodePage,
		showInNavbar: false,
		showNavBar: true,
		access: "guest",
	},
	{
		path: "/CodeBlock",
		label: "CodeBlock",
		component: CodeEditor,
		showInNavbar: false,
		showNavBar: false,
		access: "private",
	},
	{
		path: "/ChooseTask",
		label: "ChooseTask",
		component: ChooseTask,
		showInNavbar: true,
		showNavBar: true,
		access: "private",
	},
	{
		path: "/profile",
		label: "Profile",
		component: Profile,
		showInNavbar: true,
		showNavBar: true,
		access: "private",
	},
	{
		path: "/result",
		label: "Solution Result",
		component: SolutionResult,
		showInNavbar: false,
		showNavBar: true,
		access: "private",
	},
];
